# Generated by Django 5.2.7 on 2025-10-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('citizen', 'Citoyen'), ('broker', 'Courtier'), ('admin', 'Admin')], default='citizen', max_length=10),
        ),
    ]
