# Generated by Django 5.2.7 on 2025-10-26 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la station')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Quartier')),
                ('description', models.TextField(blank=True, verbose_name='Description (facultatif)')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('last_confirmation', models.DateTimeField(blank=True, null=True)),
                ('confirmation_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-last_confirmation', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_fuel', models.BooleanField(default=True, verbose_name='Carburant disponible')),
                ('fuel_type', models.CharField(choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('both', 'Les deux')], default='essence', max_length=10)),
                ('description', models.TextField(blank=True, verbose_name='Commentaire (facultatif)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='stations.station')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('station', 'user')},
            },
        ),
    ]
